import {test,expect} from '@playwright/test';
test('robot, scrub, vehicle, reverse and display controls',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('http://127.0.0.1:5173');
 await expect(page.locator('canvas')).toBeVisible();
 await page.waitForFunction(()=>window.primeStudy?.state.assemblies>20);
 await page.screenshot({path:'artifacts/robot.png'});
 await page.locator('#transform').fill('500');
 await expect(page.locator('#mode')).toHaveText('Transformation in progress');
 await page.waitForFunction(()=>Math.abs(window.primeStudy.state.progress-.5)<.001);
 await page.screenshot({path:'artifacts/midpoint.png'});
 await page.locator('#transform').fill('1000');
 await page.waitForFunction(()=>window.primeStudy.state.progress===1);
 await expect(page.locator('#mode')).toHaveText('Vehicle mode');
 await page.screenshot({path:'artifacts/truck.png'});
 await page.locator('#play').click();
 await expect(page.locator('#play-label')).toHaveText('Pause');
 await page.waitForFunction(()=>window.primeStudy.state.target<.98);
 await page.locator('#play').click();
 await page.locator('#wire').click();await expect(page.locator('#wire')).toHaveAttribute('aria-pressed','true');
 await page.locator('#wire').click();await page.locator('#rotate').click();await expect(page.locator('#rotate')).toHaveAttribute('aria-pressed','true');
 await page.locator('#reset').click();await expect(page.locator('#rotate')).toHaveAttribute('aria-pressed','false');
 await page.locator('#transform').fill('0');await page.waitForFunction(()=>window.primeStudy.state.progress===0);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 expect(errors).toEqual([]);
});
